version: '2'
services:
  hzy-caffe-torch:
    image: hzy/caffe-torch:2.23.a
    container_name: hzy_caffe_torch
    restart: always
    tty: true
    ports:
      - "8889:8888"
      - "6007:6006"
      - "8006:8886"
      - "8005:8885"
      - "8004:8884"
      - "8009:8889"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
      - ~/raychar/phpdocker/app/DeepAR_Backend/frontend/web/res/upload/ballreco:/root/BallReco
