version: '2'
services:
  hzy-dl-tightvnc:
    image: hzy/tightvnc:4.19.a
    container_name: hzy_dl_tightvnc
    privileged: true
    restart: always
    tty: true
    ports:
      - "38082:8888"
      - "36082:6006"
      - "38982:5901"
    devices:
      - /dev/nvidia0    
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
      - /home/raychar/Repos/deepar/DeepAR_Backend/frontend/web/res/upload/ballreco:/root/BallReco
