version: '2'
services:
  hzy-gnome-tiger:
    image: zl/dl-tigervnc:1.3
    restart: always
    tty: true
    ports:
      - "18002:8888"
      - "16002:6006"
      - "18903:5901"
      - "18902:5900"
      - "10002:22"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
