version: '2'
services:
  hzy:
    image: hzy/caffe-torch:2.23.a
    restart: always
    tty: true
    ports:
      - "8002:8888"
      - "6002:6008"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
